@startuml
'https://plantuml.com/deployment-diagram

actor actor [
用户
]

rectangle writeDatabaseAndMessageQueue [
写数据库和消息队列]

rectangle sendMessageQueue [
发送消息队列]

rectangle sendNotification [
发送通知]

rectangle updateCache [
更新缓存]

actor -> writeDatabaseAndMessageQueue
writeDatabaseAndMessageQueue -> sendMessageQueue
sendMessageQueue .> sendNotification
sendNotification -> updateCache

@enduml