@startuml
'https://plantuml.com/sequence-diagram

actor actor [
用户
]

rectangle writeDatabase [
写数据库]

rectangle sendShortMessage [
发送短信通知]

rectangle updateCache [
更新缓存]



actor -> writeDatabase
writeDatabase -> sendShortMessage
sendShortMessage -> updateCache

@enduml