@startuml
'https://plantuml.com/sequence-diagram

actor actor [
支付宝
]

rectangle paymentModule [
支付模块]

rectangle orderModule [
订单模块]

rectangle stockModule [
库存模块]



actor -> paymentModule : 1.支付宝回调通知
paymentModule -> orderModule : 2.通知订单模块支付完成
orderModule -> stockModule : 3.通知库存模块减库存
stockModule -> orderModule : 4.通知订单模块减库存成功
paymentModule -> actor : 3.返回success


@enduml