@startuml
'https://plantuml.com/deployment-diagram

actor actor1[
用户]
actor actor2[
用户]
actor actor3[
用户]

database database1
actor1 --> database1
actor2 --> database1
actor3 --> database1

actor actor4[
用户]
actor actor5[
用户]
actor actor6[
用户]

queue queue

database database2
actor4 --> queue
actor5 --> queue
actor6 --> queue
queue --> database2

@enduml