@startuml
'https://plantuml.com/deployment-diagram

actor actor [
用户
]

rectangle writeDatabaseAndMessageQueue [
写数据库和消息队列]

rectangle sendMessageQueue1 [
发送消息队列]

rectangle sendMessageQueue2 [
发送消息队列]

rectangle sendNotification [
发送通知]

rectangle updateCache [
更新缓存]

actor -> writeDatabaseAndMessageQueue
writeDatabaseAndMessageQueue ---> sendMessageQueue1
writeDatabaseAndMessageQueue --> sendMessageQueue2
sendMessageQueue1 .> sendNotification
sendMessageQueue2 .> updateCache

@enduml